POST {{BASE_URL}}{{PORT}}/topics/example
Content-Type: application/json
Authorization: Bearer UbCYnMAcNEe7XZ6NPbBw8sr9jt97DxwLcs42fzFXGjrYV4yzvMq9c8t4xvDeQCb8


{
    "id": "event_123123123",
    "event": "customer:created",
    "payload": {
        "first_name": "Fred",
        "last_name": "Faaren",
        "email": "fread@faaren.com"
    }
}

###
